#!/usr/bin/env python3
"""Verify the local manual-test dataset for Enterprise Remote Systems.

This script is intentionally read-only. It validates the dataset generated by
scripts/seed-manual-testdata.py using the actual SQLite schema rather than
assuming historical helper column names or id prefixes.
"""

from __future__ import annotations

import argparse
import sqlite3
import sys
from pathlib import Path
from typing import Iterable


DEFAULT_DB = "backend/data/app.db"


class VerificationIssue(Exception):
    pass


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Verify local ERS manual seed data")
    parser.add_argument("--db", default=DEFAULT_DB, help=f"SQLite database path. Default: {DEFAULT_DB}")
    return parser.parse_args()


def connect(db_path: str) -> sqlite3.Connection:
    conn = sqlite3.connect(db_path)
    conn.row_factory = sqlite3.Row
    return conn


def table_exists(conn: sqlite3.Connection, table: str) -> bool:
    return conn.execute(
        "SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?",
        (table,),
    ).fetchone() is not None


def table_columns(conn: sqlite3.Connection, table: str) -> set[str]:
    if not table_exists(conn, table):
        return set()
    return {row["name"] for row in conn.execute(f"PRAGMA table_info({table})")}


def scalar(conn: sqlite3.Connection, sql: str, params: Iterable[object] = ()) -> int | float | str | None:
    row = conn.execute(sql, tuple(params)).fetchone()
    return None if row is None else row[0]


def print_rows(title: str, rows: Iterable[sqlite3.Row]) -> None:
    print(f"\n{title}")
    printed = False
    for row in rows:
        printed = True
        print("  " + " | ".join(str(value) for value in row))
    if not printed:
        print("  <none>")


def require_count(label: str, actual: int, expected: int) -> list[str]:
    status = "OK" if actual == expected else "FAIL"
    print(f"{label:<34} {actual:>6} expected {expected:<6} {status}")
    return [] if actual == expected else [f"{label}: expected {expected}, got {actual}"]


def main() -> int:
    args = parse_args()
    db_path = Path(args.db)
    if not db_path.exists():
        print(f"Database not found: {db_path}", file=sys.stderr)
        return 2

    conn = connect(str(db_path))
    required_tables = [
        "people",
        "collaborator_journeys",
        "work_periods",
        "gold_production_entries",
        "expenses",
        "ledger_entries",
        "ledger_receipts",
    ]
    missing = [table for table in required_tables if not table_exists(conn, table)]
    if missing:
        print("Database is missing required tables: " + ", ".join(missing), file=sys.stderr)
        return 2

    issues: list[str] = []

    print("Manual seed core counts")
    people_count = int(scalar(conn, "SELECT COUNT(*) FROM people WHERE id LIKE 'manual-person-%'") or 0)
    collaborator_count = int(
        scalar(
            conn,
            """
            SELECT COUNT(*)
            FROM collaborator_journeys cj
            JOIN people p ON p.id = cj.person_id
            WHERE p.id LIKE 'manual-person-%'
            """,
        )
        or 0
    )
    work_period_count = int(scalar(conn, "SELECT COUNT(*) FROM work_periods WHERE id LIKE 'manual-work-period-%'") or 0)
    expense_count = int(scalar(conn, "SELECT COUNT(*) FROM expenses WHERE id LIKE 'manual-expense-%'") or 0)

    issues.extend(require_count("people", people_count, 70))
    issues.extend(require_count("collaborators", collaborator_count, 40))
    issues.extend(require_count("work periods", work_period_count, 14))
    issues.extend(require_count("expenses", expense_count, 80))

    print_rows(
        "\nCollaborator payment mix",
        conn.execute(
            """
            SELECT cj.payment_method_id, COUNT(*)
            FROM collaborator_journeys cj
            JOIN people p ON p.id = cj.person_id
            WHERE p.id LIKE 'manual-person-%'
            GROUP BY cj.payment_method_id
            ORDER BY cj.payment_method_id
            """
        ),
    )

    print_rows(
        "Journey date range",
        conn.execute(
            """
            SELECT MIN(cj.journey_start_date), MAX(cj.journey_start_date), COUNT(*)
            FROM collaborator_journeys cj
            JOIN people p ON p.id = cj.person_id
            WHERE p.id LIKE 'manual-person-%'
            """
        ),
    )

    future_count = int(
        scalar(
            conn,
            """
            SELECT COUNT(*)
            FROM collaborator_journeys cj
            JOIN people p ON p.id = cj.person_id
            WHERE p.id LIKE 'manual-person-%'
              AND cj.journey_start_date >= '2030-01-01'
            """,
        )
        or 0
    )
    issues.extend(require_count("future journey dates", future_count, 0))

    print_rows(
        "Work Period status mix",
        conn.execute(
            """
            SELECT status, COUNT(*)
            FROM work_periods
            WHERE id LIKE 'manual-work-period-%'
            GROUP BY status
            ORDER BY status
            """
        ),
    )

    if table_exists(conn, "accrual_runs"):
        print_rows(
            "Accrual run status mix",
            conn.execute(
                """
                SELECT ar.status, COUNT(*)
                FROM accrual_runs ar
                JOIN work_periods wp ON wp.id = ar.work_period_id
                WHERE wp.id LIKE 'manual-work-period-%'
                GROUP BY ar.status
                ORDER BY ar.status
                """
            ),
        )
        posted = int(
            scalar(
                conn,
                """
                SELECT COUNT(*)
                FROM accrual_runs ar
                JOIN work_periods wp ON wp.id = ar.work_period_id
                WHERE wp.id LIKE 'manual-work-period-%'
                  AND ar.status = 'POSTED'
                """,
            )
            or 0
        )
        pending = int(
            scalar(
                conn,
                """
                SELECT COUNT(*)
                FROM accrual_runs ar
                JOIN work_periods wp ON wp.id = ar.work_period_id
                WHERE wp.id LIKE 'manual-work-period-%'
                  AND ar.status = 'PENDING_INPUT'
                """,
            )
            or 0
        )
        issues.extend(require_count("posted accrual runs", posted, 12))
        issues.extend(require_count("pending accrual runs", pending, 2))

    print_rows(
        "Gold production by location",
        conn.execute(
            """
            SELECT location_id, COUNT(*) AS rows, ROUND(AVG(gold_grams_produced), 2) AS avg_grams
            FROM gold_production_entries
            WHERE id LIKE 'manual-gold-production-%'
            GROUP BY location_id
            ORDER BY location_id
            """
        ),
    )

    gold_rows = int(scalar(conn, "SELECT COUNT(*) FROM gold_production_entries WHERE id LIKE 'manual-gold-production-%'") or 0)
    # The seed creates gold production only for the 12 posted/accrued work periods:
    # 12 periods x 2 mine locations = 24 rows.
    issues.extend(require_count("gold production rows", gold_rows, 24))

    print_rows(
        "Ledger/current-account activity",
        conn.execute(
            """
            SELECT entry_type, direction, COUNT(*) AS rows, ROUND(SUM(amount), 4) AS total_amount
            FROM ledger_entries
            WHERE id LIKE 'manual-%'
            GROUP BY entry_type, direction
            ORDER BY entry_type, direction
            """
        ),
    )
    earning_rows = int(scalar(conn, "SELECT COUNT(*) FROM ledger_entries WHERE id LIKE 'manual-ledger-earning-%'") or 0)
    expense_rows = int(scalar(conn, "SELECT COUNT(*) FROM ledger_entries WHERE id LIKE 'manual-ledger-expense-%'") or 0)
    pix_rows = int(scalar(conn, "SELECT COUNT(*) FROM ledger_entries WHERE id LIKE 'manual-ledger-pix-%'") or 0)
    receipt_rows = int(scalar(conn, "SELECT COUNT(*) FROM ledger_receipts WHERE id LIKE 'manual-receipt-%'") or 0)
    issues.extend(require_count("earning ledger entries", earning_rows, 480))
    issues.extend(require_count("expense ledger entries", expense_rows, 80))
    issues.extend(require_count("PIX ledger entries", pix_rows, 15))
    issues.extend(require_count("receipt rows", receipt_rows, 95))

    expense_cols = table_columns(conn, "expenses")
    if "currency_code" in expense_cols:
        expense_currency_sql = """
            SELECT currency_code, COUNT(*)
            FROM expenses
            WHERE id LIKE 'manual-expense-%'
            GROUP BY currency_code
            ORDER BY currency_code
        """
    else:
        expense_currency_sql = """
            SELECT value_unit_id, COUNT(*)
            FROM expenses
            WHERE id LIKE 'manual-expense-%'
            GROUP BY value_unit_id
            ORDER BY value_unit_id
        """
    print_rows("Expense value-unit/currency mix", conn.execute(expense_currency_sql))

    if issues:
        print("\nManual seed verification failed:", file=sys.stderr)
        for issue in issues:
            print(f"  - {issue}", file=sys.stderr)
        return 1

    print("\n✅ Manual seed verification passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
